### ISSUE TITLE
Blue Box on Speed Increase Button in Chrome

### ISSUE THREAD

**Issue by IWXMon** [intelliweather/IntelliWeather.js#2]
The Speed Increase button in Chrome causes a transparent blue box (if pressed multiple times).

![issue002_chrome_blue-xpar-box_on_speed-increase-button](https://cloud.githubusercontent.com/assets/2984673/7638064/cc535fac-fa61-11e4-948e-08f226994685.jpg)

**Comment by dragan** [comment]
Similar to #1, closing for now.
