### ISSUE TITLE
Method or Example for Display of Single Frame or Still Image

### ISSUE THREAD

**Issue by IWXMon** [intelliweather/IntelliWeather.js#4]
A means to display a still image is needed for the new website. The "Playground" demo shows stills as clickthroughs to animated sequences, but what about thumbs with clickthroughs to a single high res image or cropped image?

For these image types, the play/pause buttons are not needed.

**Comment by IWXMon** [comment]
An example of these type of stills wold be channels 55 through 58, which are high res forecast maps at 5885 x 3319 pixels.

It would be interesting to have the option to join these images in a sequence to show forecast hour 12, 24, 36, then 48 in succession. Is that possible?

**Comment by dragan** [comment]
To popup a still image from a still, we just need to make sure to set series to false and remove the seriesLength from the descriptor. Using the first example as reference in the demo, this is an example descriptor:

``` javascript
{
    channel: 55,
    commands: {
      crop: [
        129,
        405,
        769,
        885
      ],
      watermarks: [
        '1_IntelliWeather'
      ],
      mode: 'max',
      quality: 85
    },
    displayWidth: 180,
    displayHeight: 140,
    series: false,
    expand: {
      channel: 55,
      displayWidth: 640,
      displayHeight: 480,
      series: false,
      commands: {
        crop: [
          129,
          405,
          769,
          885
        ],
        watermarks: [
          '1_IntelliWeather'
        ],
        mode: 'max',
        quality: 85
      }
    },
    onclick: 'popup'
  }
```

I'm not sure what the crop dimensions should be, but this should get you started.

To show them in sequence, then you will want to change the popup to be a series. If these are a special series and you don't want to display the controls, then you can pass the options to not display in the descriptor via the carouselOptions.

``` javascript
{
  expand: {
      channel: 55,
      displayWidth: 640,
      displayHeight: 480,
      series: true,
      seriesLength: 3
  },
  carouselOptions: {
    displayPlaybackControls: false,
    displaySpeedControl: false
  }
}
```

**Comment by jlawler2** [comment]
series: false in the expand (popup) descriptor throws an error, as does series: true, seriesLength: 1. Seems to work okay on the thumbnail. In FireFox:
TypeError: a.descriptor.expand is undefined
..."modal-"+l.id).css(e.extend({},i.modal,{width:a.descriptor.expand.displayWidth,h...  
jquery.....min.js (line 7, col 15686)

**Comment by jlawler2** [comment]
Also - regarding John's comment above about showing a sequence: he was wondering if it would be possible to load a "series" of "single frame" channels to display, one after the other (I think), rather than a single channel with multiple frames. I'm guessing that is well beyond the scope of this as is.
