### ISSUE TITLE
Watermarks Positioning Controls Not Working

### ISSUE THREAD

**Issue by IWXMon** [intelliweather/IntelliWeather.js#6]
Pixel offset values in the watermarks file don't seem to affect any change when modified.

**Comment by jlawler2** [comment]
Moving to appropriate issue

**Comment by dragan** [comment]
Hmm, I'll take a look and report back.

**Comment by dragan** [comment]
Pretty sure this was related to caching. Closing for now, will reopen if we need to take a closer look.
