### ISSUE TITLE
Watermarks File - Separating Logos from Map Keys

### ISSUE THREAD

**Issue by IWXMon** [intelliweather/IntelliWeather.js#7]
Is it possible to have logos vs map keys referenced individually?... & perhaps directly from the descriptor file?

Associating the two kinda defeats the purpose of interchangeability, and adding a watermarks file seems to add a layer of complexity. I assume there is a reason why descriptors can't reference these overlays directly... what is it?

**Comment by jlawler2** [comment]
Moving this here where it makes more sense...

I'm not sure why the logo and the map keys are combined? The key is related to the image type, and it is always the same for that particular type of image. It might be easier to simply define the key in the channel description?

**Comment by dragan** [comment]
I based everything off of Nathanael's original demo. I created the watermarks file with that direction in mind. We can look into changing things where it makes sense. We can create a mapping of channels to map keys that the servlet can provide or provide the info in the channel meta and send the info to the servlet. Then all that needs to be provided is the branding, which can be sent by the descriptor.

**Comment by IWXMon** [comment]
I say the simpler the better. I would have the descriptor invoke the logo, map key, & any other overlays along with their positions. Also, there may be some variance per customer for these elements & their positions. I would keep it simple & avoid passing this info via meta data. We would then, only need to look at one item (the descriptor) for all this info. to figure out what's going on for a customer's imagery.

**Comment by jlawler2** [comment]
I would link the map key to the channel in the meta data as it will never change (per image type), while the descriptor files will need editing for every client iteration. Easier to be able to manage it in one location too.

**Comment by IWXMon** [comment]
You have variance per customer as to map key location. Currently, some customers have the map key at upper right, others at lower right, & some at lower left. Channel meta data will not accomodate these differences. As for descriptor management, I'm not seeing the difficulty. When we add a new customer, we will work from a set of default descriptors, then modify some values per customer as needed. It's a once and done deal either way,... & a simple one compared to current setup methods.

**Comment by jlawler2** [comment]
This doesn't seem to be working? I can make the key go away by commenting out/deleting the whole 2nd layer node, but changing it doesn't seem to have an effect on the image it grabs or the positioning.

**Comment by jlawler2** [comment]
Maybe I needed the latest build? I just copied it over, and seems to be working now!

**Comment by jlawler2** [comment]
Yeah, it appears to be some sort of caching going on with the process at AWS. Whatever image type you click on first (radar for example) shows the correct (radar) key, but everything you click on after that will bring up the same radar key/logo combo. Clearing the local cache didn't resolve it, but if I wait for an hour or so and click on a different image type, it will bring up the correct key for that image, and then sticks to that with any subsequent image for the next hour or so (whatever the TTL is). 

This was why I kept thinking the spacing, etc wasn't working - because I was seeing a cached set of layers. We need something that updates on every instance as each image could be different on any given page/site.

**Comment by dragan** [comment]
I'm going to go ahead and close this issue. If there's any issues, let me know and we'll reopen.
